from ejercicio2 import db, Profesor, Estudiante, Curso,Seccion

p1 = Profesor(id=1,name='E. Cuadros')
p2 = Profesor(id=2,name='J. FIestas')
p3 = Profesor(id=3,name='M. Abisrror')
p4 = Profesor(id=4,name='J. Perez')
p5 = Profesor(id=5,name='K. yhin')
p6 = Profesor(id=6,name='P. Coehlo')
p7 = Profesor(id=7,name='L. Ramirez')
p8 = Profesor(id=8,name='J. Bustamante')
p9 = Profesor(id=9,name='C. Torres')
p10 = Profesor(id=10,name='P. Vargas')
db.session.add_all([p1,p2,p3,p4,p5,p6,p7,p8,p9,p10])
db.session.commit()

e1 = Estudiante(id=1,name='Isaac')
e2 = Estudiante(id=2,name='Christian')
e3 = Estudiante(id=3,name='José')
e4 = Estudiante(id=4,name='Jorge')
e5 = Estudiante(id=5,name='Piero')
e6 = Estudiante(id=6,name='Joshua')
e7 = Estudiante(id=7,name='Jake')
e8 = Estudiante(id=8,name='Juan')
e9 = Estudiante(id=9,name='Erick')
e10 = Estudiante(id=10,name='Cristopher')
db.session.add_all([e1,e2,e3,e4,e5,e6,e7,e8,e9,e10])
db.session.commit()

c1 = Curso(id=1,name='POO2',creditos=4)
c2 = Curso(id=2,name='POO1',creditos=4)
c3 = Curso(id=3,name='Matematica 1',creditos=4)
c4 = Curso(id=4,name='Matematica 2',creditos=4)
c5 = Curso(id=5,name='Matematica 3',creditos=4)
c6 = Curso(id=6,name='DBP',creditos=4)
c7 = Curso(id=7,name='Fisica 1',creditos=3)
c8 = Curso(id=8,name='Fisica 2',creditos=3)
c9 = Curso(id=9,name='ED 1',creditos=4)
c10 = Curso(id=10,name='ED 2',creditos=4)
db.session.add_all([c1,c2,c3,c4,c5,c6,c7,c8,c9,c10])
db.session.commit()

s1 = Seccion(id=1,codigo='CSDB10')
s2 = Seccion(id=2,codigo='EG0006')
s3 = Seccion(id=3,codigo='CS2B01')
s4 = Seccion(id=4,codigo='CS1DO2')
s5 = Seccion(id=5,codigo='EG005')
s6 = Seccion(id=6,codigo='CS1103')
s7 = Seccion(id=7,codigo='CS1FI4')
s8 = Seccion(id=8,codigo='GHOOO8')
s9 = Seccion(id=9,codigo='CSJTU8')
s10 = Seccion(id=10,codigo='PORRF3')
db.session.add_all([s1,s2,s3,s4,s5,s6,s7,s8,s9,s10])
db.session.commit()